library(ggplot2)
library(reshape)
raw<-read.csv("SampleData.csv", sep=",")
mm<- melt(raw,id="Person")
p<- ggplot(mm, aes(x=Person,y=value, group=variable)) 
p<- p + geom_bar(width=.8,aes(fill=variable),stat = "identity", position="dodge")
p<- p + scale_fill_manual("legend", labels=c("Male", "Female"),values = c("G1" = "#FFF2CC", "G2" = "#C9DAF8"))
p<- p + labs(title="")
p<- p + xlab("")
p<- p + ylab("Y-Axis")
p<- p + theme(panel.border=element_blank(),panel.grid.major = element_blank(), panel.grid.minor=element_blank(),panel.background=element_blank(), axis.line.x = element_line(color = "black"), axis.line.y = element_line(color="black"), text=element_text(size=25,face = "bold"))
p<- p + theme(legend.title=element_blank(), legend.background=element_rect(color = "black"))
p<- p + scale_y_continuous(limit=c(0,5), expand = c(0,0))
p
ggsave(filename = "assignment.pdf", plot = last_plot(), width=210,height=297,units="mm")